# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
parameters:
  flag-x:
    type: boolean
    default: false

jobs:
  in-config-x:
    docker:
      - image: cimg/base:stable
    steps:
      - run: echo << pipeline.parameters.flag-x >>

workflows:
  in-config-x-workflow:
    jobs:
      - in-config-x
