# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

setup: true

orbs:
  file-changes:
    commands:
      halt-if-not-changed:
        parameters:
          pattern:
            type: string
        steps:
          - checkout
          - run:
              name: "Check if files are changed"
              command: |
                echo "Fetching base branch..."
                BASE_SHA1=$(git ls-remote --symref origin HEAD | tail -n 1 | cut -f 1)

                git diff --name-only $BASE_SHA1...$CIRCLE_SHA1 | tee /tmp/changed.txt
                if [ $? -ne 0 ]; then
                  echo "Failed to get changed files. Regular job will be executed."
                  exit 0
                fi

                cat /tmp/changed.txt | grep -q -E "<< parameters.pattern >>" | tee matched.txt

                if [ -s matched.txt ]; then
                  echo "not matched. skip."
                  circleci-agent step halt

commands:
  skip-if-npm-dev-dependencies-update:
    description: "Job halted (irrelevant update: npm devDependencies)"
    steps:
      - when:
          condition:
            matches:
              pattern: "^renovate/.*devDependencies-.*"
              value: << pipeline.git.branch >>
          steps:
            - run:
                name: "Job halted (irrelevant update: npm devDependencies)"
                command: circleci-agent step halt
  skip-if-npm-dependencies-update:
    description: "Job halted (irrelevant update: npm dependencies)"
    steps:
      - when:
          condition:
            matches:
              pattern: "^renovate/.*dependencies-.*"
              value: << pipeline.git.branch >>
          steps:
            - run:
                name: "Job halted (irrelevant update: npm dependencies)"
                command: circleci-agent step halt

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/configuration-reference/#executor-job
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/configuration-reference/#steps
    steps:
      - file-changes/halt-if-not-changed:
          pattern: "src/.*"
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
      # - path-filtering/filter:
      #     base-revision: main
      #     config-path: .circleci/config-x.yml
      #     mapping: |
      #       src/x/.* flag-x true
